server.port=8080
spring.application.name=tripflow-api-service

# Server Performance & Encoding
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.servlet.multipart.max-file-size=6MB
spring.servlet.multipart.max-request-size=6MB

# JSON Date Format (Prevent timezone issues)
spring.jackson.time-zone=UTC
spring.jackson.serialization.write-dates-as-timestamps=false

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/tripflow_db}
spring.datasource.username=${POSTGRES_USER:tripflow_user}
spring.datasource.password=${POSTGRES_PASSWORD:secure_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${JPA_HIBERNATE_DDL_AUTO:update}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Logging configuration
logging.level.root=INFO
logging.level.com.tripflow=INFO
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=WARN
logging.level.org.springframework.web=WARN
logging.level.org.hibernate=WARN

# CORS Configuration
origins.frontend=${ORIGINS_FRONTEND:http://localhost}

# Cookies Configuration
cookie.domain=${COOKIE_DOMAIN:localhost}
cookie.secure=${COOKIE_SECURE:false}
cookie.same-site=${COOKIE_SAME_SITE:None}

# JWT Configuration
jwt.secret=${JWT_SECRET}

# Admin User Configuration
admin.email=${ADMIN_EMAIL}
admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}

# Unsplash API Configuration
unsplash.api.key=${UNSPLASH_API_KEY}