services:
  postgres-api:
    image: postgres:15-alpine
    container_name: tripflow-postgres-api-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata-api-test:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tripflow-network-test

  kafka:
    image: confluentinc/cp-kafka:8.1.0
    container_name: kafka-test
    restart: unless-stopped
    environment:
      KAFKA_KRAFT_MODE: "true"
      CLUSTER_ID: "0A33a0asf1dk3s-k9n-n"
      KAFKA_NODE_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    ports:
      - "9092:9092"
    volumes:
      - kafkadata-test:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - tripflow-network-test

  api-service:
    build:
      context: ../backend
      dockerfile: api-service/Dockerfile
    container_name: tripflow-api-service-test
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRINGDOC_API_DOCS_ENABLED: "true"
      SPRINGDOC_SWAGGER_UI_ENABLED: "true"
      POSTGRES_URL: jdbc:postgresql://postgres-api:5432/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ORIGINS_FRONTEND: ${ORIGINS_FRONTEND}
      COOKIE_DOMAIN: ""
      COOKIE_SECURE: false
      COOKIE_SAME_SITE: Lax
      JWT_SECRET: ${JWT_SECRET:-VGhpcyBpcyBhIHZlcnkgc2VjdXJlIGRldmVsb3BtZW50IHNlY3JldCEyMw==}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      UNSPLASH_API_KEY: ${UNSPLASH_API_KEY:-your_unsplash_api_key_here}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@admin.com}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-secure_password}
    ports:
      - "8080:8080"
    depends_on:
      postgres-api:
        condition: service_healthy
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - tripflow-network-test

  ai-service:
    build:
      context: ../backend
      dockerfile: ai-service/Dockerfile
    container_name: tripflow-ai-service-test
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: ${JWT_SECRET:-VGhpcyBpcyBhIHZlcnkgc2VjdXJlIGRldmVsb3BtZW50IHNlY3JldCEyMw==}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      AI_API_KEY: ${AI_API_KEY:-your-openai-api-key-here}
      AI_API_URL: ${AI_API_URL:-your-url-here}
      AI_API_MODEL: ${AI_API_MODEL:-your-model-here}
    ports:
      - "8081:8081"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - tripflow-network-test
  
  notification-service:
    build:
      context: ../backend
      dockerfile: notification-service/Dockerfile
    container_name: tripflow-notification-service-test
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: ${JWT_SECRET:-VGhpcyBpcyBhIHZlcnkgc2VjdXJlIGRldmVsb3BtZW50IHNlY3JldCEyMw==}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EMAIL_SENDER: ${EMAIL_SENDER:-your-email-sender-here}
      EMAIL_BREVO_API_KEY: ${EMAIL_BREVO_API_KEY:-your-email-brevo-api-key-here}
    ports:
      - "8082:8082"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - tripflow-network-test

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        PUBLIC_API_BASE_URL: http://localhost:8080
        PUBLIC_WS_BASE_URL: ws://localhost:8082
    container_name: tripflow-frontend-test
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      api-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  pgdata-api-test:
    driver: local
  kafkadata-test:
    driver: local

networks:
  tripflow-network-test:
    driver: bridge
